# Generated by Django 5.2.5 on 2025-08-15 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chat',
            new_name='chats',
        ),
    ]
