# Generated by Django 5.2.5 on 2025-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0002_rename_chat_chats'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='images')),
                ('info', models.TextField(max_length=1000)),
            ],
        ),
    ]
