# Generated by Django 5.2.5 on 2025-08-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0004_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pepar', models.URLField(max_length=500)),
            ],
        ),
    ]
