# Generated by Django 5.2.5 on 2025-08-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0006_registereduser'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='post',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
