# Generated by Django 5.2.5 on 2025-08-17 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
