# Generated by Django 5.2.5 on 2025-08-17 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0012_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
