# Generated by Django 5.2.5 on 2025-10-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learnapp', '0014_question_userscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='profileicon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ph', models.ImageField(upload_to='images')),
            ],
        ),
    ]
